# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

#if [ -f ~/.bash_aliases ]; then
#    . ~/.bash_aliases
#fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

#Setting some default colors
# Regular Colors
Black='\e[0;30m'        # Black
Red='\e[0;31m'          # Red
Green='\e[0;32m'        # Green
Yellow='\e[0;33m'       # Yellow
Blue='\e[0;34m'         # Blue
Purple='\e[0;35m'       # Purple
Cyan='\e[0;36m'         # Cyan
White='\e[0;37m'        # White
# Bold Colors
BBlack='\e[1;30m'       # Black
BRed='\e[1;31m'         # Red
BGreen='\e[1;32m'       # Green
BYellow='\e[1;33m'      # Yellow
BBlue='\e[1;34m'        # Blue
BPurple='\e[1;35m'      # Purple
BCyan='\e[1;36m'        # Cyan
BWhite='\e[1;37m'       # White

#Custom Prompt
export PS1="\[${BGreen}\]\n\u@\h:\W \$ \[${BWhite}\]"

#Aliases
alias cls="clear"
alias ls="ls --color"
alias syslog="journalctl"
#alias up="sudo yum update"
alias hibernate="systemctl hibernate"

#Aliasing sudo to allow use with aliases! 
alias sudo="sudo "

#LFS related information
#alias arch-boot="VBoxManage startvm ArchLinux --type headless"
#alias arch-poweroff="VBoxManage controlvm ArchLinux poweroff"
#alias arch-login="ssh ronnie@192.168.52.41"
#export LFS="/mnt/lfs"

#Adding the JAVA_HOME variable for Android Studio
##If using openJdk...and crappy fonts
#export JAVA_HOME="/usr/lib/jvm/java-1.7.0-openjdk"
##If using Oracle JDK
#export JAVA_HOME="/usr/java/default/"

#I'm just too careless!!
alias rm="rm -i"

#Android command line tools
export PATH="$PATH:~/.local/bin:~/Android/sdk/tools:~/Android/sdk/platform-tools"
#Adding Genymotion and Android-Studio aliases
alias android-studio="~/Android/android-studio/bin/studio.sh"
#alias genymotion="~/Android/genymotion/genymotion"

#Use this to enable and disable the touchpad
alias et="xinput --enable 'SynPS/2 Synaptics TouchPad'"
alias dt="xinput --disable 'SynPS/2 Synaptics TouchPad'"

#Setting the default libvirt URI
#export LIBVIRT_DEFAULT_URI=qemu:///system

#Setting a default Picture directory for Gnome 3
#export PICTURES="/home/ronnie/Pictures"

#IBus Settings
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULE=ibus

#Updating pacman mirrorlist
alias mu="reflector --verbose -l 20 -p http --sort rate --save /etc/pacman.d/mirrorlist"

#Raspberry Pi SSH Login
alias rpilog="ssh -p 6253 ronnie@RonniePi.local"

#Setting default editor
export EDITOR=vim

#Setting the build directory for AUR packages
#export BUILDDIR=~/Builds/aur

#Setting the 'command not found' hook from pkgfile
if [ -f /bin/pkgfile ]; then
	source /usr/share/doc/pkgfile/command-not-found.bash
fi

#Setting autocd for bash
shopt -s autocd
